default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: travis909
  password: 'Daytona97!'

development:
  <<: *default
  database: logfit_development

test:
  <<: *default
  database: logfit_test

# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: logfit_production
  username: travis909
  password: <%= ENV['LOGFIT_DATABASE_PASSWORD'] %>
